### ISSUE TITLE
Python process communication error when computing gradients

### ISSUE THREAD

**Issue by schmrlng** [malmaud/TensorFlow.jl#9]
Thanks for prototyping this package! I'm getting this error trying to construct (not yet run) a reasonably simple RNN model:
```
LoadError: On worker 2:
PyError (:PyObject_Call) None

 in pyerr_check at /home/schmrlng/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /home/schmrlng/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /home/schmrlng/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#62 at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:547
 in _pycall at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:535
 in #pycall#66 at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:569
 in pycall at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:569
 in #call#67 at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:572
 in py_gradients at /home/schmrlng/.julia/v0.5/TensorFlow/src/py.jl:45
 in #65 at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:824
 in #625 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #624 at ./event.jl:68
while loading In[23], in expression starting on line 39

 in #remotecall_fetch#606(::Array{Any,1}, ::Function, ::Function, ::Base.Worker) at ./multi.jl:1070
 in remotecall_fetch(::Function, ::Base.Worker) at ./multi.jl:1062
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1080
 in gradients(::TensorFlow.Operation, ::Array{Any,1}) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:823
 in compute_gradients(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Operation, ::Void) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:33
 in #minimize#1(::Void, ::Void, ::String, ::Function, ::TensorFlow.train.AdamOptimizer, ::TensorFlow.Operation) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:25
 in minimize(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Operation) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:22
```

In trying to construct a minimal reproduction case (minimizing the Frobenius norm of a variable), I get this different error (maybe related?):

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-linux-gnu

julia> using TensorFlow
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally

julia> Z = Variable(ones(4,4))
TensorFlow.Variable(<Operation 'node1' dtype=Float64>,<Operation 'node1/Assign' dtype=Float64>)

julia> loss = reduce_mean(Z .* Z)
<Node node4:1 dtype=Float64>

julia> optimizer = train.AdamOptimizer()
TensorFlow.train.AdamOptimizer(0.01,0.9,0.999,1.0e-8,"adam")

julia> train_op = train.minimize(optimizer, loss)
WARNING: Unrecognized attribute DstT
WARNING: Unrecognized attribute SrcT
ERROR: Tensorflow error: Status: NodeDef missing attr 'DstT' from Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: gradients/node4_grad/Cast = Cast[SrcT=DT_INT32](gradients/node4_grad/floordiv_1)

 in check_status(::TensorFlow.Status) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:118
 in TensorFlow.Operation(::TensorFlow.NodeDescription) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:387
 in TensorFlow.Operation(::TensorFlow.tensorflow.NodeDef) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:520
 in extend_graph(::TensorFlow.Graph, ::Array{Any,1}) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:93
 in gradients(::TensorFlow.Tensor, ::Array{Any,1}) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:897
 in compute_gradients(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor, ::Void) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:33
 in #minimize#1(::Void, ::Void, ::String, ::Function, ::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:25
 in minimize(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:22

julia> Z = Variable(ones(4,4))    # trying again from the start
TensorFlow.Variable(<Operation 'node7' dtype=Float64>,<Operation 'node7/Assign' dtype=Float64>)

julia> loss = reduce_mean(Z .* Z)
<Node node10:1 dtype=Float64>

julia> optimizer = train.AdamOptimizer()
TensorFlow.train.AdamOptimizer(0.01,0.9,0.999,1.0e-8,"adam")

julia> train_op = train.minimize(optimizer, loss)
ERROR: On worker 2:
MethodError: no method matching getindex(::Void, ::Symbol)
 in collect at ./array.jl:304
 in py_gradients at /home/schmrlng/.julia/v0.5/TensorFlow/src/py.jl:47
 in #59 at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:895
 in #625 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #624 at ./event.jl:68
 in #remotecall_fetch#606(::Array{Any,1}, ::Function, ::Function, ::Base.Worker) at ./multi.jl:1070
 in remotecall_fetch(::Function, ::Base.Worker) at ./multi.jl:1062
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1080
 in gradients(::TensorFlow.Tensor, ::Array{Any,1}) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:894
 in compute_gradients(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor, ::Void) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:33
 in #minimize#1(::Void, ::Void, ::String, ::Function, ::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:25
 in minimize(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:22
```

The corresponding python version:
```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
>>> Z = tf.Variable(tf.ones((4,4)))
>>> loss = tf.reduce_mean(tf.mul(Z, Z))
>>> opt = tf.train.AdamOptimizer()
>>> train_op = opt.minimize(loss)
>>>
>>> with tf.Session() as sess:
...     sess.run(tf.initialize_all_variables())
...     for i in range(100):
...         print sess.run([loss, train_op])
...
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.2155
pciBusID 0000:02:00.0
Total memory: 4.00GiB
Free memory: 3.91GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x2f23bc0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties:
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.367
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.85GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 980, pci bus id: 0000:01:00.0)
[1.0, None]
[0.99800104, None]
[0.99600405, None]
...etc...
```

**Comment by malmaud** [comment]
Thanks for trying it out! At least the second error I've already fixed locally. Not sure about the first one - when I push my fix for the second, you can try it out and see if it still errors.

**Comment by schmrlng** [comment]
Cool, thanks - I look forward to trying out the fix!

**Comment by malmaud** [comment]
Try now on the latest master

**Comment by schmrlng** [comment]
Definite progress - I'm now able to call `train.minimize` successfully on the simple norm minimization example, but only once (see the log below), and I can `run` the result provided I splat or vcat it. I'm still seeing the original 
```
LoadError: On worker 2:
PyError (:PyObject_Call) None
...
```
trace on my RNN model; I'll see what I can do now in terms of constructing a minimal reproduction case.

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-linux-gnu

julia> using TensorFlow
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally

julia> begin
           Z = Variable(ones(4,4))
           loss = reduce_mean(Z .* Z)
           optimizer = train.AdamOptimizer()
           train_op = train.minimize(optimizer, loss)
       end
WARNING: Unrecognized attribute _class
3-element Array{TensorFlow.Tensor,1}:
 <Tensor node28:1 dtype=Float64>
 <Tensor node29:1 dtype=Float64>
 <Tensor node30:1 dtype=Float64>

julia> let sess = Session()
           run(sess, initialize_all_variables())
           for i in 1:3
               val, _ = run(sess, [loss; train_op])    # [loss, train_op...] also works
               println(val)
           end
       end
1.0
0.9377546017366026
0.857332537349711

julia> let sess = Session()
           run(sess, initialize_all_variables())
           for i in 1:3
               val, _ = run(sess, [loss, train_op])
               println(val)
           end
       end
ERROR: MethodError: Cannot `convert` an object of type Array{TensorFlow.Tensor,1} to an object of type TensorFlow.Port
This may have arisen from a call to the constructor TensorFlow.Port(...),
since type constructors fall back to convert methods.
 in TensorFlow.Port(::Array{TensorFlow.Tensor,1}) at ./sysimg.jl:53
 in collect_to!(::Array{TensorFlow.Port,1}, ::Base.Generator{Array{Any,1},Type{TensorFlow.Port}}, ::Int64, ::Int64) at ./array.jl:337
 in _collect(::Array{Any,1}, ::Base.Generator{Array{Any,1},Type{TensorFlow.Port}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:318
 in run(::TensorFlow.Session, ::Array{Any,1}, ::Dict{Any,Any}) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:714
 in run(::TensorFlow.Session, ::Array{Any,1}) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:730
 in macro expansion; at ./REPL[4]:4 [inlined]
 in anonymous at ./<missing>:?

julia> begin
           Z = Variable(ones(4,4))
           loss = reduce_mean(Z .* Z)
           optimizer = train.AdamOptimizer()
           train_op = train.minimize(optimizer, loss)
       end
ERROR: On worker 2:
MethodError: no method matching getindex(::Void, ::Symbol)
 in collect at ./array.jl:304
 in py_gradients at /home/schmrlng/.julia/v0.5/TensorFlow/src/py.jl:47
 in #59 at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:925
 in #625 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #624 at ./event.jl:68
 in #remotecall_fetch#606(::Array{Any,1}, ::Function, ::Function, ::Base.Worker) at ./multi.jl:1070
 in remotecall_fetch(::Function, ::Base.Worker) at ./multi.jl:1062
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1080
 in gradients(::TensorFlow.Tensor, ::Array{Any,1}) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:924
 in compute_gradients(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor, ::Void) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:33
 in #minimize#1(::Void, ::Void, ::String, ::Function, ::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:25
 in minimize(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:22
```

**Comment by schmrlng** [comment]
Calling ```TensorFlow.set_def_graph(Graph())``` seems to fix the error in redefining the norm minimization example. Alternatively (and I think, equivalently), calling ```sess = Session(Graph())``` is what allows the logistic regression example in README.md to be run multiple times without error.

**Comment by schmrlng** [comment]
It seems that my problem lies in some interaction between `slice` and `train.minimize`:

```julia
julia> let sess = Session(Graph())
           Z = Variable(ones(4,4))
           Zpart = slice(Z, [0,0], [-1,2])
           loss = reduce_mean(Zpart .* Zpart)
           optimizer = train.AdamOptimizer()
           train_op = train.minimize(optimizer, loss)

       #     run(sess, initialize_all_variables())
       #     for i in 1:10
       #         val, _ = run(sess, [model["loss"]; model["train_op"]], Dict(model["X"] => rand(Float32,6,10), model["Y"] => rand(Float32,6,3)))
       #         println(val)
       #     end
       end
ERROR: On worker 2:
PyError (:PyObject_Call) None

 in pyerr_check at /home/schmrlng/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /home/schmrlng/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /home/schmrlng/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#62 at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:547
 in _pycall at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:535
 in #pycall#66 at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:569
 in pycall at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:569
 in #call#67 at /home/schmrlng/.julia/v0.5/PyCall/src/PyCall.jl:572
 in py_gradients at /home/schmrlng/.julia/v0.5/TensorFlow/src/py.jl:45
 in #59 at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:925
 in #625 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #624 at ./event.jl:68
 in #remotecall_fetch#606(::Array{Any,1}, ::Function, ::Function, ::Base.Worker) at ./multi.jl:1070
 in remotecall_fetch(::Function, ::Base.Worker) at ./multi.jl:1062
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1080
 in gradients(::TensorFlow.Tensor, ::Array{Any,1}) at /home/schmrlng/.julia/v0.5/TensorFlow/src/core.jl:924
 in compute_gradients(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor, ::Void) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:33
 in #minimize#1(::Void, ::Void, ::String, ::Function, ::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:25
 in minimize(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/schmrlng/.julia/v0.5/TensorFlow/src/train.jl:22
```

**Comment by malmaud** [comment]
Thanks for getting the minimal example together - I'll look into it soon.

**Comment by malmaud** [comment]
Alright, think this is fixed now.
